-- Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.


-- Database DDL for Complaint Server (PostgreSQL). Mirrors mysql.sql; see it for the column notes.

CREATE TABLE IF NOT EXISTS COMPLAINT (
  COMPLAINT_ID       CHAR(36)     NOT NULL,
  ORG_ID             VARCHAR(255) NOT NULL,
  USER_ID            VARCHAR(255) NOT NULL,
  USER_NAME          VARCHAR(255) DEFAULT NULL,
  REFERENCE_ID       VARCHAR(32)  NOT NULL,
  CATEGORY           VARCHAR(64)  NOT NULL,
  PRIORITY           VARCHAR(16)  NOT NULL,
  STATUS             VARCHAR(32)  NOT NULL DEFAULT 'OPEN',
  DESCRIPTION        TEXT         NOT NULL,
  CREATED_TIME       BIGINT       NOT NULL,
  UPDATED_TIME       BIGINT       NOT NULL,
  STATUTORY_DUE_TIME BIGINT       NOT NULL,
  PRIMARY KEY (COMPLAINT_ID, ORG_ID),
  CONSTRAINT UQ_COMPLAINT_REFERENCE UNIQUE (ORG_ID, REFERENCE_ID),
  CONSTRAINT CHK_COMPLAINT_PRIORITY CHECK (PRIORITY IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
  CONSTRAINT CHK_COMPLAINT_STATUS CHECK (STATUS IN
      ('OPEN', 'IN_PROGRESS', 'WAITING_ON_CLIENT', 'AWAITING_INTERNAL_REVIEW', 'RESOLVED'))
);
CREATE INDEX IF NOT EXISTS IDX_COMPLAINT_ORG_STATUS ON COMPLAINT (ORG_ID, STATUS);
CREATE INDEX IF NOT EXISTS IDX_COMPLAINT_ORG_USER ON COMPLAINT (ORG_ID, USER_ID);

CREATE TABLE IF NOT EXISTS COMPLAINT_EVENT (
  COMPLAINT_EVENT_ID CHAR(36)     NOT NULL,
  ORG_ID             VARCHAR(255) NOT NULL,
  COMPLAINT_ID       CHAR(36)     NOT NULL,
  ACTOR_USER_ID      VARCHAR(255) DEFAULT NULL,
  ACTOR_USER_NAME    VARCHAR(255) DEFAULT NULL,
  ACTOR_ROLE         VARCHAR(32)  NOT NULL,
  IS_PUBLIC          BOOLEAN      NOT NULL DEFAULT TRUE,
  COMMENT            TEXT         DEFAULT NULL,
  FROM_STATUS        VARCHAR(32)  DEFAULT NULL,
  TO_STATUS          VARCHAR(32)  DEFAULT NULL,
  ACTION_TIME        BIGINT       NOT NULL,
  PRIMARY KEY (COMPLAINT_EVENT_ID, ORG_ID),
  CONSTRAINT FK_CE_COMPLAINT FOREIGN KEY (COMPLAINT_ID, ORG_ID) REFERENCES COMPLAINT (COMPLAINT_ID, ORG_ID),
  CONSTRAINT CHK_CE_ACTOR_ROLE CHECK (ACTOR_ROLE IN ('USER', 'COMPLAINT_OFFICER', 'SYSTEM'))
);
CREATE INDEX IF NOT EXISTS IDX_CE_COMPLAINT_TIME ON COMPLAINT_EVENT (COMPLAINT_ID, ORG_ID, ACTION_TIME);

CREATE TABLE IF NOT EXISTS COMPLAINT_ATTACHMENT (
  ATTACHMENT_ID      CHAR(36)     NOT NULL,
  ORG_ID             VARCHAR(255) NOT NULL,
  COMPLAINT_ID       CHAR(36)     NOT NULL,
  COMPLAINT_EVENT_ID CHAR(36)     DEFAULT NULL,
  FILE_NAME          VARCHAR(255) NOT NULL,
  FILE_CONTENT_TYPE  VARCHAR(128) NOT NULL,
  FILE_DATA          BYTEA        NOT NULL,
  IS_PUBLIC          BOOLEAN      NOT NULL DEFAULT TRUE,
  CREATED_TIME       BIGINT       NOT NULL,
  PRIMARY KEY (ATTACHMENT_ID, ORG_ID),
  CONSTRAINT FK_CA_COMPLAINT FOREIGN KEY (COMPLAINT_ID, ORG_ID) REFERENCES COMPLAINT (COMPLAINT_ID, ORG_ID),
  CONSTRAINT FK_CA_EVENT FOREIGN KEY (COMPLAINT_EVENT_ID, ORG_ID)
      REFERENCES COMPLAINT_EVENT (COMPLAINT_EVENT_ID, ORG_ID)
);
CREATE INDEX IF NOT EXISTS IDX_CA_COMPLAINT ON COMPLAINT_ATTACHMENT (COMPLAINT_ID, ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_CA_EVENT ON COMPLAINT_ATTACHMENT (COMPLAINT_EVENT_ID, ORG_ID);
